spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    filter: stat,wall
    initialSize: 5
    minIdle: 1
    maxActive: 30
server:
  port: 8088